OnlineStore/Controllers/NavigationController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Models.Product;

namespace OnlineStore.Controllers
{
    public class NavigationController : Controller
    {
        private IProduct iprod;

        public NavigationController(IProduct ipr)
        {
            iprod = ipr;
        }

        public PartialViewResult CategoryMenu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = iprod.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

OnlineStore/Views/Shared/ProdInfo.cshtml
@model OnlineStore.Models.Product.Product

    <div class="well">
        <h4>
            <strong><span>@Model.Name</span></strong>
            <span class="pull-right label">$@Model.Price</span>
        </h4>
        
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.ProductId)
                @Html.Hidden("url", Request.Url.PathAndQuery)
                <input type="submit" class="btn-selected" value="Add to cart">
            </div>
        }
        <h5>@Model.Description</h5>
    </div>

OnlineStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OnlineStore</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/my-style.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-custom" role="navigation">
        <a class="navbar-brand" href="#">OnlineStore</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-lg-2">
            @Html.Action("CategoryMenu", "Navigation")
        </div>
        <div class="col-lg-1">
        </div>
        <div class="col-lg-7">
            @RenderBody()
        </div>
    </div>
</body>
</html>